language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t phuongminh2303/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true phuongminh2303/react-test npm test -- --coverage

after_success: 
  - docker build -t phuongminh2303/multi-client ./client
  - docker build -t phuongminh2303/multi-nginx ./nginx
  - docker build -t phuongminh2303/multi-server ./server
  - docker build -t phuongminh2303/multi-worker ./worker
  # Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push image to docker hub
  - docker push phuongminh2303/multi-client
  - docker push phuongminh2303/multi-nginx
  - docker push phuongminh2303/multi-server
  - docker push phuongminh2303/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalke
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-732409576677
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
